### ISSUE TITLE
Pihole-Dark on Docker Version?

### ISSUE THREAD

**Issue by XxAcielxX** [lkd70/PiHole-Dark#14]
Hello,

Thanks for making such a lovely dark theme for the Pihole, but I wanted know is it compatible with Docker Version of Pihole?

If not can you somehow get in touch with my Pihole Devs so both of you can find a way to themes work natively so we can change them from the Admin CP.

**Regards~**

**Comment by andrewkdinh** [comment]
Just run `docker exec -it <PIHOLE_CONTAINER_ID> bash` and run the same commands from the README as you would if it were a local machine.

**Comment by XxAcielxX** [comment]
Alright I tried your above mentioned guide and this happened:

http://pastehere.xyz/iDD6WyXw/

Oh I'm on Arch ARM, running docker.

**WARNING** Don't run it on Docker, running above commands broke my Pihole Container.

**Comment by andrewkdinh** [comment]
That `install.sh` script you ran is for setting up the Pi-hole container when it is first started. It broke your Pi-hole container because it tried installing it from scratch (e.g. the `installPihole` line). 

Restart your Docker container then follow the instructions from the [README](https://github.com/lkd70/PiHole-Dark#easy-install) to first download the dark script (with the same name `install.sh`), then execute it. 

```bash
docker exec -it <PIHOLE_CONTAINER_ID> bash

# From the README (you may or may not need sudo)
cd /var/www/html/
sudo wget https://raw.githubusercontent.com/lkd70/PiHole-Dark/master/install.sh
sudo chmod +x install.sh
sudo ./install.sh
# Follow the onscreen instructions!
```

**Comment by XxAcielxX** [comment]
I tried it, but now I ran into this issue
```
sudo wget https://raw.githubusercontent.com/lkd70/PiHole-Dark/master/install.sh
--2019-08-17 23:08:31--  https://raw.githubusercontent.com/lkd70/PiHole-Dark/master/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 0.0.0.0, ::
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|0.0.0.0|:443... failed: Connection refused.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|::|:443... failed: Connection refused.
```

So now I **Install** it the manual way:
1) `docker exec - it <pihole container id> bash`
2) `cd /var/www/html`
3) `cp -f admin/style/vendor/AdminLTE.min.css admin/style/vendor/AdminLTE.min.bkp.css`
4) `git clone https://github.com/lkd70/PiHole-Dark.git temp`
5) `rm -f admin/style/vendor/AdminLTE.min.css`
6) `cp temp/admin/style/vendor/AdminLTE.min.css admin/style/vendor/AdminLTE.min.css`
7) `cp temp/admin/style/vendor/AdminLTE.css admin/style/vendor/AdminLTE.css`
8) `rm -rf temp/`

**Uninstall** manually:
1) `rm - fadmin/style/vendor/AdminLTE.css admin/style/vendor/AdminLTE.min.css`
2) `cp admin/style/vendor/AdminLTE.min.bkp.css admin/style/vendor/AdminLTE.min.css`

**Comment by andrewkdinh** [comment]
Looks like it didn't work the first way because your Pi-hole container is blocking `raw.githubusercontent.com`, as you can't connect to that domain but can `git clone` from `github.com`. Perhaps query your pihole logs to see if is being blocked.

**Comment by XxAcielxX** [comment]
Ah, you're very correct. It was being blocked (face palm). All is working now. Thanks again

**Comment by andrewkdinh** [comment]
You’re welcome. Feel free to close this issue now that it’s resolved
