### ISSUE TITLE
Won't uninstall..

### ISSUE THREAD

**Issue by DJ-Anakin** [lkd70/PiHole-Dark#19]
I upgraded to Pi-Hole 5 yesterday, and one of the devs added that they were gonna add a dark mode to the next version. Someone commented a link to this git. I installed it fine, but I think i'd rather not use it after trying it for a bit. 

I followed the Easy Uninstall steps, but when I got to `git reset --hard` it returned `fatal: Unable to create '/var/www/html/admin/.git/index.lock': Permission denied`

Any ideas?

**Comment by TheFlemoid** [comment]
Have you tried running it with sudo?  So "sudo git reset --hard"?

/var is usually owned by root:root, so it won't be able to modify anything in there without root permissions.

**Comment by DJ-Anakin** [comment]
No, because i'm a frigging noob. :\

That worked. Thank you. 👍
