### ISSUE TITLE
Installer Hiccup?

### ISSUE THREAD

**Issue by deathbybandaid** [lkd70/PiHole-Dark#2]
`pi@raspberrypi:/var/www/html $ sudo ./install.sh`
`Create a backup of the current files? (Y/n): y`
`Backup completed!`
`Install LKD70's Dark Theme now? (Y/n): y`
`Cloning into 'temp'...`
`remote: Counting objects: 106, done.`
`remote: Compressing objects: 100% (18/18), done.`
`remote: Total 106 (delta 0), reused 0 (delta 0), pack-reused 86`
`Receiving objects: 100% (106/106), 74.19 KiB | 0 bytes/s, done.`
`Resolving deltas: 100% (20/20), done.`
`Checking connectivity... done.`
`cp: cannot stat ‘temp/admin/scripts/pi-hole/js/index.js’: No such file or directory`
`cp: cannot stat ‘temp/admin/img/back.png’: No such file or directory`
`All done!`

**Comment by deathbybandaid** [comment]
also, it broke all of the stats from loading

**Comment by lkd70** [comment]
Cheers, I've yet to update the installer. Simply dropping in the adminLTE.min.css for now should do the trick.

**Comment by lkd70** [comment]
**https://github.com/lkd70/PiHole-Dark/commit/414e6c47930383244339aa130279a5aa44e38887** should fix it, you can rollback your files using: `pihole -r`

**Comment by deathbybandaid** [comment]
just installed it,,, looks great!
