### ISSUE TITLE
Web Version 3.2 breaks Settings > System page

### ISSUE THREAD

**Issue by skylineKid712** [lkd70/PiHole-Dark#4]
The new version of the admin pages sort of breaks the theme on the Settings pages, especially Settings > System page
![pihole](https://user-images.githubusercontent.com/6434803/33700628-64442fee-dae8-11e7-9bc0-baa32565150a.PNG)

**Comment by lkd70** [comment]
Ruh-roh! We can'y be having that now, can we?

Done some minor (rather messy) changes to this to at least make it bearable... hopefully your eyes won't burn as much now. Thanks for the feedback!

**Comment by skylineKid712** [comment]
@lkd70 What's the best way to update? Should I just follow the installation instructions again or is there an update command?

**Comment by lkd70** [comment]
Hey, sorry that it wasn't so clear, yes following the install instructions again should work to update. If you run in to any issues, try the uninstall method to start from a blank canvas :). If you experience any issues, let me know.

**Comment by raid5** [comment]
This seems to be resolved. Verified with a fresh install of PiHole-Dark.
