### ISSUE TITLE
Add black background

### ISSUE THREAD

**Issue by azlux** [lkd70/PiHole-Dark#5]
Hi,
I think you can add 
```
.layout-boxed {
    background: url('../../img/boxed-bg.jpg') repeat fixed;
    background-color: rgba(8, 8, 14, 0.95);
    background-blend-mode: overlay;
}
```
to make the background pattern darker.
(your customizations are awesome)
Az

**Comment by aqw789** [comment]
Hi,
Personally I have replace the original background by this.
![boxed-bg](https://user-images.githubusercontent.com/12912375/38189157-16b78384-365f-11e8-9deb-c2f1e076c8c9.jpg)

**Comment by lkd70** [comment]
Please check out the FAQ for background info: https://github.com/lkd70/PiHole-Dark#q-yuck-why-is-the-background-still-white-how-could-you-do-this-to-me
