### ISSUE TITLE
Not Working with latest release

### ISSUE THREAD

**Issue by C4Wiz** [lkd70/PiHole-Dark#6]
Theme does not install correctly on latest release:

cannot create regular file 'admin/style/vendor/AdminLTE.css': No such file or directory

**Comment by C4Wiz** [comment]
has development stopped?

**Comment by lkd70** [comment]
Hello, forgive me for the slow reply. I'll look in to setting up the latest and greatest build now and take a poke at her, see if I can't get this working for you again :)

**Comment by C4Wiz** [comment]
Im sorry it was my fault, i was working from /var/www/html/admin/

**Comment by lkd70** [comment]
I'm glad to hear that, no need to be sorry - means less work for me 😃. If you have any suggestions or run in to issues, do let me know. I've not been using pihole for a while, so some elements may need updating.
