### ISSUE TITLE
Revert to Stock Theme

### ISSUE THREAD

**Issue by C4Wiz** [lkd70/PiHole-Dark#7]
i used your git reset --hard method and ran into issues. i was instructed by the pihole team to use this instead:

Make sure you are not in /var/www/html/admin.

```
sudo rm -rf /var/www/html/admin
sudo git clone https://github.com/pi-hole/AdminLTE.git /var/www/html/admin
```

all good now!

**Comment by lkd70** [comment]
Thanks, this has been added to the `install.sh` script as an uninstall option.
